# Generated by Django 5.0.1 on 2024-02-01 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_suppliers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='enabled',
            new_name='is_active',
        ),
    ]
