# Generated by Django 5.0.1 on 2024-02-01 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='enabled',
            new_name='is_active',
        ),
    ]
