# Generated by Django 5.0.1 on 2024-01-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_slug_supplierproduct_and_more'),
        ('suppliers', '0002_alter_supplier_options_alter_supplier_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(blank=True, through='products.SupplierProduct', to='suppliers.supplier'),
        ),
    ]
